name: Build from source # workflow name
description: Workflow for building the library from the source

runs:
  using: composite

  steps: # tasks

    - name: Build library # build CPngLib
      shell: bash
      run:
        pip3 install -e .
        # python setup.py bdist
        # cp $(find build/lib* -maxdepth 0)/pnglib/cpnglib/*.so pnglib/cpnglib/ || true
        # cp $(find build/lib* -maxdepth 0)/pnglib/cpnglib/*.pyd pnglib/cpnglib/ || true
        # ls